name: CICD testing-4

on:
  pull_request:
    branches: [ Development ]
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - name: Compile
        run: echo Hello, world!
  DeployDevelopment:
    name: Deploy to Dev
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge Build - > Development
        uses: devmasx/merge-branch@v1.3.1
        with:
          time: '5m'
          from_branch: sanchit20199120-patch-4
          target_branch: Development
          period: 1
          github_token: ${{ secrets.GITHUB_TOKEN }}
  DeployStaging:
    name: Deploy to Staging
    needs: [DeployDevelopment]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge Development - > Staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: Development
          target_branch: Staging
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
    
    

