name: release
on:
  push:
    branches: [ Production ]
jobs:
  release:
    name:  Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Creaye GitHub release
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
